#pragma once

#include "triton/backend/backend_common.h"

#define LOG_VERBOSE(MSG) LOG_MESSAGE(TRITONSERVER_LOG_VERBOSE, MSG)
#define LOG_ERROR(MSG) LOG_MESSAGE(TRITONSERVER_LOG_ERROR, MSG)
#define LOG_INFO(MSG) LOG_MESSAGE(TRITONSERVER_LOG_INFO, MSG)
